### ISSUE TITLE
database schema

### ISSUE THREAD

**Issue by salahzidi** [SimonMarquis/InternalAppStore#10]
Is there a file that contains the database schema?

**Comment by SimonMarquis** [comment]
Hi @salahzidi, schemas are located in `firebase/database/*`.

**Comment by salahzidi** [comment]
Hi, thank you for your quick answer. How can I add my own applications to the appstore?

**Comment by SimonMarquis** [comment]
Please follow the [deployment steps](https://github.com/SimonMarquis/InternalAppStore#deploy). Everything should be explained there.

**Comment by salahzidi** [comment]
It's a little ambiguous when filling database and storage fields, if you join a screenshot of their placement in the firebase console it will be better

**Comment by SimonMarquis** [comment]
As explained in the README you should use the firebase CLI which will be responsible to upload the database schema.

**Comment by SimonMarquis** [comment]
APKs and icons must be uploaded through the web app as a user with admin role.
Take a look at the screenshots from the readme:
- https://github.com/SimonMarquis/InternalAppStore/blob/master/art/web_applications_admin.png
- https://github.com/SimonMarquis/InternalAppStore/blob/master/art/web_applications_add.png
- https://github.com/SimonMarquis/InternalAppStore/blob/master/art/web_applications_edit.png

**Comment by salahzidi** [comment]
OK, I got it, thanks a lot!
