### ISSUE TITLE
Error: "permission_denied at /store: Client doesn't have permission to access the desired data."

### ISSUE THREAD

**Issue by rave1502** [SimonMarquis/InternalAppStore#5]
Apologies if I am opening a non-issue.
My requirement is only to have an authenticated web-page from where my restricted users can download the application. Hence I am only using the firebase-hosting module from your application.

The problem is when I execute the hosted application, I get the following error:

```
Error: "permission_denied at /store: Client doesn't have permission to access the desired data."
    i index.esm.js:641
    onComplete index.esm.js:628
    startListening index.esm.js:12677
    sendListen_ index.esm.js:11791
    onDataMessage_ index.esm.js:12046
    onDataMessage_ index.esm.js:11331
    onPrimaryMessageReceived_ index.esm.js:11325
    connReceiver_ index.esm.js:11226
    appendFrame_ index.esm.js:10831
    handleIncomingFrame index.esm.js:10881
    onmessage index.esm.js:10778
index.js:1694:9
    ensureUserIsAllowed index.js:1694
    b auth.esm.js:17
    Ct auth.esm.js:20
    Rt auth.esm.js:20
    Yb auth.esm.js:19
    pt auth.esm.js:13

Error: "Not allowed"
    ensureUserIsAllowed index.js:1722
    b auth.esm.js:17
    Ct auth.esm.js:20
    Rt auth.esm.js:20
    Yb auth.esm.js:19
    pt auth.esm.js:13
index.js:1751:21
    onUserLoggedIn http://localhost:5000/index.js:1751
```

Can you please help. Please know I am really new to web-development. All I can say is that we are getting user token from the auth service on user login.

**Comment by SimonMarquis** [comment]
This message is displayed because your user is trying to access a protected field of the Firebase Database.
You might have to update the corresponding rules.

You can take a look at the 'public' rules:
https://github.com/SimonMarquis/InternalAppStore/blob/master/firebase/database/database-public.rules.json

**Comment by rave1502** [comment]
Hi Simon, Can you please give me an example of what changes I need to do?

**Comment by SimonMarquis** [comment]
You need to apply appropriate read/write rules to the Realtime Database.
If you're not familiar with these rules, read this documentation: https://firebase.google.com/docs/database/security/
