### ISSUE TITLE
Hi am a beginner can you please tell me what to do here

### ISSUE THREAD

**Issue by amanijoseph87** [SimonMarquis/InternalAppStore#6]
I try so many things here but nothing I get a message your store is empty but I don't have any admin write, please help am new in firebase.

https://github.com/SimonMarquis/InternalAppStore/blob/20dce92699f00a429b75306b82fc08b522995e96/firebase/storage/storage-private.rules#L8-L9

**Comment by amanijoseph87** [comment]
// THIS IS NOT AN ISSUE AM SORRY FOR THIS IS// THIS IS JUST A BEGINNER ASK FOR HELP//

I really want to test this but am stack, what to do to add admin to be able to upload apk, please am just a beginner in all firebase rules and CLI. I deploy all files and folder I already have set up a login and sign up and the domain rule I already setup I start to lose it one this step

`firebase database:update /admins --data '{"<admin-uid>" : "<admin-email>"}'
# On Windows, create a JSON file instead (unsupported JSON input)
firebase database:update /admins update.json`

I don't know what to do here, do I replace <admin-uid> with UID code from the user or insert <admin-uid> as a table where I can insert admin UID for admin later, the same goes for admin-email

![appnzuri – Database – Firebase console - Google Chrome 11_3_2019 8_26_43 AM (2)](https://user-images.githubusercontent.com/21230918/68080836-4c097500-fe14-11e9-9c43-7ac35bd7771c.png)

Then I stack on the rules what do I need to add there, and what do you mean on the DELETE section I try so many rules I read on _stack_ but nothing works. Please am new on Firebase please help.

![appnzuri – Database – Firebase console - Google Chrome 11_3_2019 8_29_13 AM (2)](https://user-images.githubusercontent.com/21230918/68080834-41e77680-fe14-11e9-9ac2-459bda7cf0de.png)

And the last part is this 

![appnzuri – Database – Firebase console - Google Chrome 11_3_2019 8_33_22 AM (2)](https://user-images.githubusercontent.com/21230918/68080855-c0441880-fe14-11e9-99bd-4041b865ca4d.png)

How can i make the app public for viewing but private for uploading, just like the [demo ](https://public-app-store.web.app/)

Please again am sorry for this but I am just a beginner and i really like to learn and use this as part of my project to supply my demo apps to my friends. I will be much appreciated if you take the time to write me a few words on what to do as a beginner.

**Comment by SimonMarquis** [comment]
Hi @amanijoseph87, here is how you're supposed to update the admins object in the firebase database:

```bash
firebase database:update /admins --data '{"t2NkauI1EpVQ..." : "amanijoseph..."}'
```

And for the firebase storage rules, you should add your uid to both lists (images and apks):

```
          allow write: if // Admin uids
                          request.auth.uid in [ "t2NkauI1EpVQ..." ]
```

If you want to replicate the demo (public app store), you should use these 2 files as template:
- https://github.com/SimonMarquis/InternalAppStore/blob/master/firebase/storage/storage-public.rules
- https://github.com/SimonMarquis/InternalAppStore/blob/master/firebase/database/database-public.rules.json

**Comment by amanijoseph87** [comment]
Thank you very much for this nice support, I manage to make the app work, one more thing what can I do to increase upload size or to add just a link to another source.

**Comment by amanijoseph87** [comment]
Soory one more thing the app is not working after sign in the app close how can i make like the demo app

**Comment by amanijoseph87** [comment]
I want people to be able to see the app just like on the demo, wrt now it shows only login from and when someone login its say your not allow here

**Comment by SimonMarquis** [comment]
Are you talking about the Android app or the web app?
Also, can you post screenshots as well, or even logs so it's easier to debug.

**Comment by amanijoseph87** [comment]
It seems that the web app is not public so no one can see any uploaded apps available. Here is your demo app, its public because you don't need to login to see the apps.

![App Store - Google Chrome 11_3_2019 4_43_37 PM (2)](https://user-images.githubusercontent.com/21230918/68086122-51d57980-fe59-11e9-8b11-c1fa68e1c68e.png)

Here is the app am working on, when you view it without login this is what you see

![App Store - Google Chrome 11_3_2019 4_46_15 PM (2)](https://user-images.githubusercontent.com/21230918/68086138-877a6280-fe59-11e9-902f-458c19235351.png)

But then, when non-admin account login you will see this page

![App Store - Google Chrome 11_3_2019 4_47_24 PM (2)](https://user-images.githubusercontent.com/21230918/68086159-d32d0c00-fe59-11e9-8259-b59df93f97cd.png)
 
And on Android App, it's the same the difference is when you log in on an app the app close ( not crush just close like it was supposed to do that when non-admin account login ) I just want the app to be like this 

![WhatsApp Image 2019-11-03 at 4 51 40 PM](https://user-images.githubusercontent.com/21230918/68086241-a4fbfc00-fe5a-11e9-97bd-0033e998f1f1.jpeg)

**Comment by SimonMarquis** [comment]
- It seems you didn't properly configured the parameters as explained in the readme:
  + Android: [Store.kt](https://github.com/SimonMarquis/InternalAppStore/blob/master/app/src/main/java/fr/smarquis/appstore/Store.kt#L18-L30)
  + Web: [index.js](https://github.com/SimonMarquis/InternalAppStore/blob/master/firebase/hosting/index.js#L5-L23)
- Make sure both storage/database rules are correctly set from the console

**Comment by amanijoseph87** [comment]
I make the rule on a web app and on Android app both true 

`AppStore.CONFIG = {
  allowAnonymousUsers: true,
  allowUnverifiedEmail: true,
  firebaseUi: {
    signInFlow: "popup",
    credentialHelper: firebaseui.auth.CredentialHelper.NONE,
    signInOptions: [
      firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      {
        provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
        requireDisplayName: true
      }
    ]`

**Comment by amanijoseph87** [comment]
But I keep seeing the sign-in page, on the android app it says Permission denied

**Comment by amanijoseph87** [comment]
I see my mistake is I change the domain this allows only the domain to work with a system, I see the way it works you have to log in to see the apps or maybe it's because of the @domain change, what can I do to allow all people to log in and can i add phone number verification instead of email.

**Comment by SimonMarquis** [comment]
Again, please use the public version of rules files:
- https://github.com/SimonMarquis/InternalAppStore/blob/master/firebase/storage/storage-public.rules
- https://github.com/SimonMarquis/InternalAppStore/blob/master/firebase/database/database-public.rules.json

**Comment by amanijoseph87** [comment]
Do i need to add uid on these files

**Comment by SimonMarquis** [comment]
Yes, you must add your own uid if you want to have any 'write' permission.

**Comment by amanijoseph87** [comment]
What about this file https://github.com/SimonMarquis/InternalAppStore/blob/master/firebase/storage/storage-public.rules because I edit this by adding uid on the required field. I am supposed to do that..?

**Comment by SimonMarquis** [comment]
Yes.
And also update this with the corresponding filenames: https://github.com/SimonMarquis/InternalAppStore/blob/20dce92699f00a429b75306b82fc08b522995e96/firebase/firebase.json#L2-L7

**Comment by amanijoseph87** [comment]
Sorry am a beginner on Firebase, can you tell me where am I suppose to add these line ..? can you send me the updated file with these rules or can you tell me below which line should I add this. I am so sorry again for this.....

**Comment by amanijoseph87** [comment]
> Yes.
> And also update this with the corresponding filenames:
> 
> https://github.com/SimonMarquis/InternalAppStore/blob/20dce92699f00a429b75306b82fc08b522995e96/firebase/firebase.json#L2-L7

If this is from firebase.json it's like that because I didn't change anything on that file or rename any directory

**Comment by SimonMarquis** [comment]
# firebase/firebase.json:
```
{
  "database": {
    "rules": "database/database-public.rules.json"
  },
  "storage": {
    "rules": "storage/storage-public.rules"
  },
  "hosting": {
    "public": "hosting",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ],
    "headers": [
      {
        "source": "**/*.@(js|html)",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "max-age=0"
          }
        ]
      }
    ]
  },
  "functions": {
    "predeploy": [
      "npm --prefix functions run lint"
    ]
  }
}
```

# firebase/storage/storage-public.rules
```
service firebase.storage {
  match /b/{bucket}/o {
    match /applications {
      match /{applicationId} {
        match /image {
          allow read;
          allow write: if // Admin uids
                          request.auth.uid in [ "YOUR UID HERE" ]
                          &&
                            (
                              // DELETE
                              request.resource == null
                              // PUT/UPDATE with these restrictions
                              || (request.resource.size <= 2 * 1024 * 1024 && request.resource.contentType.matches('image/.*'))
                            )
                          ;
        }
        match /versions {
          match /{versionId} {
            allow read;
            allow write: if // Admin uids
                            request.auth.uid in [ "YOUR UID HERE" ]
                            &&
                              (
                                // DELETE
                                request.resource == null
                                // PUT/UPDATE with these restrictions
                                || (request.resource.size <= 100 * 1024 * 1024 && request.resource.contentType == 'application/vnd.android.package-archive')
                              )
                            ;
          }
        }
      }
    }
  }
}
```

# firebase/database/database-public.rules.json
```
{
  "rules": {
    "admins": {
      "$uid": {}
    },
    "checks": {
      "admin": {
        ".read": "root.child('admins').hasChild(auth.uid)"
      },
      "emailVerified": {
        ".read": "auth.token.email_verified == true"
      },
      "emailNotVerified": {
        ".read": "auth.token.email_verified == false"
      },
    },
    "store": {
      ".write": "root.child('admins').hasChild(auth.uid)",
      ".read": "true",
      "applications": {
        "$application_id": {
          // PUSH/UPDATE if has fields ['description', 'name', 'packageName']
          ".validate": "newData.hasChildren(['description', 'name', 'packageName'])",
          "description": {
            ".validate": "newData.isString()"
          },
          "image": {
            ".validate": "newData.isString()"
          },
          "name": {
            ".validate": "newData.isString() && newData.val().length > 0"
          },
          "packageName": {
            // PackageName regex
            ".validate": "newData.isString() && newData.val().matches(/^([A-Za-z]{1}[A-Za-z\\d_]*\\.)*[A-Za-z][A-Za-z\\d_]*$/)"
          },
          "link_1": {
            ".validate": "newData.hasChildren(['name', 'uri']) && newData.child('name').isString() && newData.child('uri').isString()"
          },
          "link_2": {
            ".validate": "newData.hasChildren(['name', 'uri']) && newData.child('name').isString() && newData.child('uri').isString()"
          },
          "link_3": {
            ".validate": "newData.hasChildren(['name', 'uri']) && newData.child('name').isString() && newData.child('uri').isString()"
          },
          "link_4": {
            ".validate": "newData.hasChildren(['name', 'uri']) && newData.child('name').isString() && newData.child('uri').isString()"
          },
          "link_5": {
            ".validate": "newData.hasChildren(['name', 'uri']) && newData.child('name').isString() && newData.child('uri').isString()"
          },
          "silent": {
            ".validate": "newData.val() == null || newData.isBoolean()"
          },
          "$other": {
            ".validate": false
          }
        }
      },
      "versions": {
        "$application_id": {
          "$version_id": {
            // PUSH/UPDATE if application_id exists and has fields ['description', 'name', 'timestamp']
            ".validate": "root.child('store').child('applications').child($application_id).exists() && newData.hasChildren(['description', 'name', 'timestamp'])",
            "apkRef": {
              ".validate": "newData.isString()"
            },
            "apkSize": {
              ".validate": "newData.isNumber()"
            },
            "apkGeneration": {
              ".validate": "newData.isNumber()"
            },
            "apkUrl": {
              ".validate": "newData.isString()"
            },
            "description": {
              ".validate": "newData.isString()"
            },
            "name": {
              // Semver regex
              ".validate": "newData.isString() && newData.val().matches(/^(\\d+)(\\.(\\d+)(\\.(\\d+))?)?(-(.+))?$/)"
            },
            "timestamp": {
              ".validate": "newData.isNumber()"
            },
            "silent": {
              ".validate": "newData.val() == null || newData.isBoolean()"
            },
            "downloads": {
              ".validate": "newData.isNumber()"
            },
            "installs": {
              ".validate": "newData.isNumber()"
            },
            "$other": {
              ".validate": false
            }
          }
        }
      },
      "$other": {
        ".validate": false
      }
    },
    "analytics": {
      "downloads": {
        "$application_id": {
          "$version_id": {
            ".validate": "root.child('store').child('applications').child($application_id).exists() && root.child('store').child('versions').child($application_id).child($version_id).exists()",
            "$uid": {
              ".write": "$uid === auth.uid",
              ".validate": "newData.isNumber()"
            }
          }
        }
      },
      "installs": {
        "$application_id": {
          "$version_id": {
            ".validate": "root.child('store').child('applications').child($application_id).exists() && root.child('store').child('versions').child($application_id).child($version_id).exists()",
            "$uid": {
              ".write": "$uid === auth.uid",
              ".validate": "newData.isNumber()"
            }
          }
        }
      },
      "$other": {
        ".validate": false
      }
    },
    "$other": {
      ".validate": false
    }
  }
}
```

**Comment by amanijoseph87** [comment]
Nice, thank you so much its is working now... Can I add phone verification method.?

**Comment by amanijoseph87** [comment]
As the is no need to login to download the app I think there is no need for login, next update please add user will have to log in to download but they can view the app.

**Comment by SimonMarquis** [comment]
Yes, you can add it to from the firebase console.
You might have to handle this on the webapp and Android app as well.

**Comment by amanijoseph87** [comment]
> Yes, you can add it to from the firebase console.
> You might have to handle this on the webapp and Android app as well.

How can I do that if you don't mind

**Comment by amanijoseph87** [comment]
So sorry for today am sure you're tired of this closing and opening.. am so sorry for this and your time too

**Comment by SimonMarquis** [comment]
Check the documentation:
- https://firebase.google.com/docs/auth/android/phone-auth
- https://firebase.google.com/docs/auth/web/phone-auth
