### ISSUE TITLE
How can i change list layout to grid (Android App) 

### ISSUE THREAD

**Issue by jacklinejohn** [SimonMarquis/InternalAppStore#7]
I real like the project, but i have a little knowledge in Kotlin. I want to change list style to grid style on Android app. Can you please give me the code to add on your android app to change the style to be grid.

**Comment by SimonMarquis** [comment]
You can take a look at the official documentation about `LayoutManager`s for `RecyclerView`s here: https://developer.android.com/guide/topics/ui/layout/recyclerview
