### ISSUE TITLE
i dont know for no reson i keep get you are not allowed here

### ISSUE THREAD

**Issue by tweakdoor** [SimonMarquis/InternalAppStore#8]
i added my self as admin by udid but still keep get not allowed here

**Comment by SimonMarquis** [comment]
What is the error message from the web console?

**Comment by tweakdoor** [comment]
i am getting this app store is currently  empty and there is no +  to add new application i am using windows so i could not add admin i guess i need to do this # On Windows, create a JSON file instead (unsupported JSON input)
firebase database:update /admins update.json

but i do nothing
