### ISSUE TITLE
cant install apps

### ISSUE THREAD

**Issue by tweakdoor** [SimonMarquis/InternalAppStore#9]
i have done everything and everything work fine but when i try to installl from my app install keep freezing working but its not installing i dont understand why

**Comment by tweakdoor** [comment]
-10-04 11:37:01.631 13450-13450/mod99.tweak.door W/ClassMapper: No setter/field for downloads found on class fr.smarquis.appstore.Version


this error i am getting in andriod

**Comment by SimonMarquis** [comment]
I don't think this is actually what's triggering the freeze. This log message is only a warning.
Also, there isn't supposed to be a field `downloads` on the `Version` class.
Can you give more details about this?
A complete Logcat, screencast of the issue would help as well, and what modifications from the original source code you've done.
